# Generated by Django 5.0.4 on 2024-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appuser_firstname_alter_appuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
