# Generated by Django 5.0.6 on 2024-05-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_dislikes_post_liked_by_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
