# Generated by Django 5.0.6 on 2024-05-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_comments_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
