# Generated by Django 5.0.6 on 2024-05-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_post_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
